### ISSUE TITLE
Name the board and programming language

### ISSUE THREAD

**Issue by jsseng** [jsseng/arduino_robot#40]
Post your top 2 animals.  Be sure to check for any related projects with similar names.

**Comment by aaronkeen** [comment]
Rhinoceros
Wallaby

**Comment by ooee123** [comment]
Aardvark
Flamingo

**Comment by aaronkeen** [comment]
I almost said Flamingo.  Mostly because of the idea of frying the board and the obvious link 'Flaming-o'.

**Comment by jsseng** [comment]
Toucan
Puffin 

Although I just found a couple of bird-named kids robot projects:  Finch and Hummingbird.  There was also a Puffin web browser.

**Comment by lanahodzic** [comment]
Bumble bee and that language could be Buzz

Or

Cow and the language could be Moo
