### ISSUE TITLE
decide board color

### ISSUE THREAD

**Issue by jsseng** [jsseng/arduino_robot#72]
We can get a custom board color.  I was ordering the default of Green with White text.  The available colors are:  Blue, Red, Black, Yellow, White.  The board text is also available in:   Blue, Red, Black

I have heard of text being hard to read when you don't use the standard white on green.  I've never seen a yellow board in person, so I don't know how crazy that would look.

**Comment by ooee123** [comment]
Omg, yellow board with black text? That's very bee-like
